name: fetch_tray
description: A set of flutter_hooks to make fetching and working with data from apis easier.
version: 0.2.3
homepage: https://github.com/marqably/fetch_tray
repository: https://github.com/marqably/fetch_tray

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.4
  mockito: ^5.2.0
  logger: ^1.1.0
  dio: ^5.2.1+1

dev_dependencies:
  test:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
