name: fetch_tray
description: An opinionated, easy to use, and flexible HTTP client for Dart, which can be used with hooks.
version: 0.3.2
homepage: https://github.com/marqably/fetch_tray
repository: https://github.com/marqably/fetch_tray

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  mockito: ^5.2.0
  logger: ^1.1.0
  dio: ^5.2.1+1

dev_dependencies:
  test:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
